#!/usr/bin/env bash
# Start the local dev stack: agent-service (FastAPI on :8010) + web (Next.js on :3000).
#
# Single source of truth for configuration: the repo-root .env file.
#   - Backend vars (Supabase, RabbitMQ, LLM provider) are passed to uvicorn.
#   - Frontend vars (NEXT_PUBLIC_*, proxy wiring) are SYNCED into web/.env.local,
#     which Next.js reads at build/dev time.
#
# Requirements:
#   - .env at repo root (copy from .env.example if absent; keep out of git)
#   - Supabase local running (postgres on 54322) — `supabase start`
#   - RabbitMQ on 5672 (optional for chat-only dev; required for skill/sandbox runs)
#   - `uv` and `pnpm` on PATH

set -euo pipefail
cd "$(dirname "$0")/.."   # repo root

ROOT_ENV=".env"
WEB_ENV="web/.env.local"

if [[ ! -f "$ROOT_ENV" ]]; then
  echo "error: $ROOT_ENV not found. Copy .env.example to .env and fill it in." >&2
  exit 1
fi

# --- Load the single source of truth (STRICT KEY=value lines) ---
# shellcheck disable=SC1091
set -a            # export every var as it's sourced
source "$ROOT_ENV"
set +a

# --- Required for the BFF proxy + backend ---
: "${AGENT_SERVICE_URL:?AGENT_SERVICE_URL is required in $ROOT_ENV}"
: "${AGENT_INTERNAL_TOKEN:?AGENT_INTERNAL_TOKEN is required in $ROOT_ENV}"
: "${SUPABASE_ANON_KEY:?SUPABASE_ANON_KEY is required in $ROOT_ENV}"
AGENT_PORT="${AGENT_SERVICE_URL##*:}"          # e.g. 8010 from http://localhost:8010

# The backend talks to Supabase server-side; prefer 127.0.0.1 over localhost.
SUPABASE_URL="${SUPABASE_URL:-http://127.0.0.1:54321}"
SUPABASE_JWKS_URL="${SUPABASE_URL%/}/auth/v1/.well-known/jwks.json"

# --- Preflight ---
command -v uv   >/dev/null 2>&1 || { echo "error: uv is required (agent-service)."   >&2; exit 1; }
command -v pnpm >/dev/null 2>&1 || { echo "error: pnpm is required (web)."           >&2; exit 1; }

# --- Sync the frontend env (Next.js reads NEXT_PUBLIC_* + proxy vars from web/.env.local) ---
cat > "$WEB_ENV" <<EOF
# Generated by scripts/start.sh from $ROOT_ENV — do not edit by hand.
NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL:-${SUPABASE_URL/localhost/127.0.0.1}}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY:-$SUPABASE_ANON_KEY}
NEXT_PUBLIC_USE_REAL_API=${NEXT_PUBLIC_USE_REAL_API:-true}
AGENT_SERVICE_URL=$AGENT_SERVICE_URL
AGENT_INTERNAL_TOKEN=$AGENT_INTERNAL_TOKEN
EOF

# --- Cleanup on exit: kill both children ---
PIDS=()
cleanup() {
  local pid
  for pid in "${PIDS[@]:-}"; do
    [[ -n "$pid" ]] && kill "$pid" 2>/dev/null || true
  done
  wait 2>/dev/null || true
}
trap cleanup EXIT INT TERM

# --- Start agent-service ---
echo "▶ Starting agent-service on :$AGENT_PORT ..."
(
  cd agent-service
  AGENT_INTERNAL_TOKEN="$AGENT_INTERNAL_TOKEN" \
  SUPABASE_URL="$SUPABASE_URL" \
  SUPABASE_ANON_KEY="$SUPABASE_ANON_KEY" \
  SUPABASE_JWKS_URL="$SUPABASE_JWKS_URL" \
  RABBITMQ_URL="${RABBITMQ_URL:-amqp://guest:guest@127.0.0.1:5672/}" \
  AGENT_PROVIDER_BASE_URL="${AGENT_PROVIDER_BASE_URL:-}" \
  AGENT_PROVIDER_API_KEY="${AGENT_PROVIDER_API_KEY:-}" \
  AGENT_PROVIDER_MODEL="${AGENT_PROVIDER_MODEL:-}" \
  uv run uvicorn app.main:app --host 127.0.0.1 --port "$AGENT_PORT" --reload
) &
PIDS+=("$!")

# Wait for agent-service to accept requests.
echo "   waiting for agent-service health ..."
for _ in $(seq 1 30); do
  if curl -fsS "http://127.0.0.1:$AGENT_PORT/healthz" >/dev/null 2>&1; then
    echo "   agent-service up on :$AGENT_PORT"
    break
  fi
  if ! kill -0 "${PIDS[0]}" 2>/dev/null; then
    echo "error: agent-service exited during startup." >&2
    exit 1
  fi
  sleep 1
done

# --- Start web ---
echo "▶ Starting web on :3000 ..."
(
  cd web
  pnpm dev
) &
PIDS+=("$!")

echo
echo "✓ Stack starting. Frontend: http://localhost:3000  |  Agent API: http://localhost:$AGENT_PORT"
echo "  Press Ctrl-C to stop both."
wait
